- id: email_jeff_arrive_home
  alias: 'Email Jeff arrive Home'
  trigger:
    platform: zone
    entity_id: device_tracker.jeff_pixel
    zone: zone.Home
    event: enter
  action:
    - service: notify.emailjeff
      data:
        message: "Welcome home Jeff!"

- id: email_rachel_arrive_home
  alias: 'Email Rachel arrive Home'
  trigger:
    platform: zone
    entity_id: device_tracker.rachel_iphone
    zone: zone.Home
    event: enter
  action:
    - service: notify.emailjeff
      data:
        message: "Rachel arrived at Home"
#    - service: notify.emailrachel
#      data:
#        message: "Welcome home Rachel!"

- id: front_light_on_sunset
  alias: "Front Light On Sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "00:15:00"
  action:
    - service: switch.turn_on
      entity_id: switch.front_light_switch

- id: front_light_off_sunrise
  alias: "Front Light Off Sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:15:00"
  action:
    - service: switch.turn_off
      entity_id: switch.front_light_switch

- id: sun_room_camera_motion
  alias: "Sun Room Camera Motion"
  trigger:
    platform: state
    entity_id: 
      - sensor.amcrest_camera_motion_detected
    from: "False"
    to: "True"
  action:
    - service: notify.emailjeff
      data:
        message: "Motion Detected in Sun Room!"

- id: sun_room_door_open
  alias: "Sun Room Door Open"
  trigger:
    platform: state
    entity_id: 
      - sensor.sun_room_door_alarm_level
    from: "0"
    to: "255"
  condition:
#  - condition: time
#    after: '09:00:00'
#    before: '15:00:00'
#    weekday:
#    - mon
#    - tue
#    - wed
#    - thu
  - condition: and
    conditions:
      - condition: template
        value_template: "{{ states('device_tracker.jeff_pixel') != 'home' }}"
      - condition: template
        value_template: "{{ states('device_tracker.rachel_iphone') != 'home' }}"
  action:
    - service: notify.emailjeff
      data_template:
        title: 'Home Assistant Notification'
        message: "Sun Room Door is open!"
#        data:
#          push:
#            category: camera
#          entity_id: camera.amcrest_camera
    - service: notify.ios_rachel_iphone
      data:
        title: 'Sun Room Door is Open'
        message: 'Someone opened the Sun Room Door! at {{now().strftime("%H:%M:%S")}}'
    - service: notify.mypushbullet
      data:
        title: 'Sun Room Door Open'
        message: 'The Sun Room Door was opened! at {{now().strftime("%H:%M:%S")}}'

- id: front_door_open
  alias: "Front Door Open"
  trigger:
    platform: state
    entity_id: 
      - sensor.front_door_alarm_level
    from: "0"
    to: "255"
  action:
    - service: notify.emailjeff
      data_template:
        title: 'Home Assistant - Door Open'
        message: "Front Door is open!"

- id: den_door_open
  alias: "Den Door Open"
  trigger:
    platform: state
    entity_id: 
      - sensor.den_door_alarm_level
    from: "0"
    to: "255"
  action:
    - service: notify.emailjeff
      data_template:
        title: 'Home Assistant - Door Open'
        message: "Den Door is open!"

- id: garage_entry_open
  alias: "Garage Entry Open"
  trigger:
    platform: state
    entity_id: 
      - sensor.garage_entry_alarm_level
    from: "0"
    to: "255"
  action:
    - service: notify.emailjeff
      data_template:
        title: 'Home Assistant - Door Open'
        message: "Garage Entry is open!"
#        data:
#          push:
#            category: camera
#          entity_id: camera.amcrest_camera

- id: test_door_open
  alias: "Test Door Open"
  trigger:
    platform: state
    entity_id: 
      - sensor.test_door_alarm_level
    from: "0"
    to: "255"
  action:
    - service: notify.emailjeff
      data_template:
        title: 'Home Assistant - Door Open'
        message: 'Test Door is open! {{now().strftime("%H:%M:%S")}}'
    - service: notify.mypushbullet
      data:
        title: Test Door Open
        message: 'The Test Door was opened right now! {{now().strftime("%H:%M:%S")}}'
        