homeassistant:
  # Customization file
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/www/camera
    - /config/tts

#Show Hass.io tab
hassio:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  login_attempts_threshold: 6
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.1.98

# Checks for available updates
updater:

#ifttt:
#  key: !secret ifttt_key

discovery:
mobile_app:

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'DOOR_ALARM'
            title: 'Door Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: !secret ddwrt_username
    password: !secret ddwrt_password
  - platform: ddwrt
    host: 192.168.1.2
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    
proximity:
  home:
    ignored_zones:
      - gmi
    devices:
      - person.jeff
      - person.rachel
    tolerance: 50
    unit_of_measurement: mi

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    base_url: !secret google_say_base_url

cast:
system_health:
person:
stream:

automation: !include_dir_merge_list automations
camera: !include camera.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_list sensors

amcrest:
  - host: 192.168.1.212
    username: !secret amcrest_username
    password: !secret amcrest_password
    binary_sensors:
      - motion_detected
      
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

zoneminder:
  host: 192.168.1.200
#  ssl: true
#  verify_ssl: true
  username: !secret zoneminder_username
  password: !secret zoneminder_password
  
switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor
    
binary_sensor:
  - platform: hikvision
    host: 192.168.1.203
    username: !secret hikcamera_username
    password: !secret hikcamera_password
  - platform: hikvision
    host: 192.168.1.204
    username: !secret hikcamera_username
    password: !secret hikcamera_password        
  - platform: hikvision
    host: 192.168.1.205
    username: !secret hikcamera_username
    password: !secret hikcamera_password        

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml
  debug: true

wake_on_lan:

media_player:
  - platform: onkyo
    host: 192.168.1.20
    name: Onkyo
    sources:
      fm: 'FM'
      am: 'AM'
      cd: 'Chromecast'
      dlna: 'DLNA'
      internet-radio: 'NET'

webostv:
  name: Living Room TV
  host: 192.168.1.22
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "A8:23:FE:37:1B:02"

alarm_control_panel:
  - platform: manual
    name: Alarm Panel
#    code: !secret alarm_code

google_assistant:
  project_id: !secret google_asst_project_id

light:
  - platform: flux_led
    devices: 
      192.168.1.31:
        name: DenLED

cover:
  platform: opengarage
  covers:
      garage:
        host: 192.168.1.32
        name: volvo
        device_key: !secret openGarageKey

input_boolean:
  front_door_motion_button:
    name: Front Door Motion Button
    initial: off
    icon: mdi:doorbell-video
  cooper_door_button:
    name: Cooper Door Button
    initial: off
    icon: mdi:dog-side
  dexter_button:
    name: Dexter Garage Button
    initial: off
    icon: mdi:car-estate
  driveway_button:
    name: Driveway Button
    initial: off
    icon: mdi:car-estate
  pixel_garage_proximity:
    name: Pixel Garage Proximity
    initial: off
    icon: mdi:garage
  cooper_is_home:
    name: Cooper Is Home
    initial: off
    icon: mdi:dog-side
  vacation:
    name: Vacation
    initial: off
    icon: mdi:wallet-travel

climate:
  platform: honeywell
  username: !secret honeywell_username
  password: !secret honeywell_password
  scan_interval: 900
  away_heat_temperature: 62
  away_cool_temperature: 83

schluter:
  username: !secret schluter_username
  password: !secret schluter_password

weather:
  - platform: darksky
    api_key: !secret darksky_api

recorder:
  db_url: mysql://hass:blahBlah9876@core-mariadb/homeassistant?charset=utf8
  purge_keep_days: 15
  exclude:
    domains: 
      - zwave
    entities:
      - sun.sun
      - sensor.obihai_last_reboot
      - cover.volvo
