homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 307
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www/camera

# Show links to resources in log and frontend
#introduction:

# Discover some devices automatically
#discovery: false

#Show Hass.io tab
hassio:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret baseurl
  login_attempts_threshold: 4
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true
  
ifttt:
  key: !secret ifttt_key

#mqtt:
#  broker: localhost
#  port: 1883
#  client_id: home-assistant-9
#  username: !secret mqtt_username
#  password: !secret mqtt_password

#mqtt:
#  discovery: true
#  discovery_prefix: homeassistant

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'DOOR_ALARM'
            title: 'Door Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

device_tracker:
  - platform: gpslogger
  - platform: ddwrt
    host: 192.168.1.1
    username: !secret ddwrt_username
    password: !secret ddwrt_password

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

cast:

# Cloud
#cloud:

automation: !include_dir_merge_list automations
camera: !include camera.yaml
group: !include groups.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_list sensors
zone: !include zones.yaml

amcrest:
  - host: 192.168.1.202
    username: !secret amcrest_username
    password: !secret amcrest_password
    sensors:
      - motion_detector
#      - sdcard
#      - ptz_preset


ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

zoneminder:
  host: 192.168.1.200
#  ssl: true
#  verify_ssl: true
  username: !secret zoneminder_username
  password: !secret zoneminder_password
  
switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor
    
binary_sensor:
  - platform: hikvision
    host: 192.168.1.203
    username: !secret hikrearcam_username
    password: !secret hikrearcam_password
        
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml
  debug: true

media_player:
  - platform: onkyo
    host: 192.168.1.20
    name: Onkyo
    sources:
      fm: 'FM'
      am: 'AM'
      cd: 'Chromecast'
      dlna: 'DLNA'
      internet-radio: 'NET'
  - platform: webostv
    name: Living Room TV
    host: 192.168.1.21
    
alarm_control_panel:
  - platform: manual
    name: Alarm Panel
#    code: !secret alarm_code

google_assistant:
  project_id: !secret google_asst_project_id
  api_key: !secret google_asst_api_key

light:
  - platform: flux_led
    devices: 
      192.168.1.31:
        name: DenLED

cover:
  platform: opengarage
  covers:
      garage:
        host: 192.168.1.32
        name: volvo
        device_key: !secret openGarageKey

input_boolean:
  cooper_door_button:
    name: Cooper Door Button
    initial: off
    icon: mdi:dog-side

climate:
  platform: honeywell
  username: !secret honeywell_username
  password: !secret honeywell_password
  region: 'us'
  scan_interval: 900
  away_temperature: 64
  away_heat_temperature: 64
  away_cool_temperature: 82


